# Generated by Django 4.2.21 on 2026-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_track_created_at_track_release_date_track_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytrack',
            name='gcs_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='gcs_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
