# Generated by Django 4.2.21 on 2026-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_status_video_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gcs_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
