# Generated by Django 4.2.21 on 2026-06-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_body_alter_website_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=400, null=True)),
                ('width', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
