# Generated by Django 4.2.21 on 2026-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websiteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='query',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
