# Generated by Django 4.2.21 on 2026-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gcs_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
