# Generated by Django 4.2.21 on 2026-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
