# Generated by Django 4.2.21 on 2026-06-29 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('post_link', models.URLField()),
                ('subreddit', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('nsfw', models.BooleanField(default=False)),
                ('spoiler', models.BooleanField(default=False)),
                ('ups', models.IntegerField(default=0)),
                ('preview', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_memes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
