# Generated by Django 4.2.21 on 2026-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='meme_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='post_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.TextField(),
        ),
    ]
