# Generated by Django 4.2.21 on 2026-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_alter_meme_meme_id_alter_meme_post_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
