# Generated by Django 4.2.21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
