# Generated by Django 4.2.21 on 2026-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_voicemessage_messagevoice_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('groupchat', 'Group Chat')], default='direct', max_length=20),
        ),
    ]
