# Generated by Django 4.2.21 on 2026-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chat_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_saved_messages',
            field=models.BooleanField(default=False),
        ),
    ]
