# Generated by Django 4.2.21 on 2026-06-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chat_is_saved_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='transcribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='transcription_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='transcription_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_requested', max_length=20),
        ),
    ]
