# Generated by Django 4.2.21 on 2025-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_created_at_link_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='time_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
