# Generated by Django 4.2.21 on 2025-07-01 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('title_type', models.CharField(blank=True, max_length=50)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('num_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('directors', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('date_rated', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
        migrations.AddField(
            model_name='movie',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='impressions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_rated', models.DateField(blank=True, null=True)),
                ('watched', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='movies.imdbmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
