name: Deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_GCP }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -n "${{ secrets.GCE_PUBLIC_IP }}" ]; then
          ssh-keyscan -H ${{ secrets.GCE_PUBLIC_IP }} >> ~/.ssh/known_hosts
        else
          echo "Error: GCE_PUBLIC_IP secret is not set."
          exit 1
        fi

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Deploy to Server
      run: |
        if [ -z "${{ secrets.GCP_USER }}" ] || [ -z "${{ secrets.GCE_PUBLIC_IP }}" ]; then
          echo "Error: GCP_USER or GCE_PUBLIC_IP secret is missing."
          exit 1
        fi
        ssh ${{ secrets.GCP_USER }}@${{ secrets.GCE_PUBLIC_IP }} "mkdir -p ~/litloop_backend_v2"
        rsync -avz --exclude '.git' --exclude 'env' --exclude 'venv' --exclude 'venv_3.9' --exclude '__pycache__' --exclude 'uploaded_media' --exclude 'static' ./ ${{ secrets.GCP_USER }}@${{ secrets.GCE_PUBLIC_IP }}:~/litloop_backend_v2/
        ssh ${{ secrets.GCP_USER }}@${{ secrets.GCE_PUBLIC_IP }} "cd ~/litloop_backend_v2 && bash deploy/deploy_script.sh"
